import os
from datetime import datetime
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)

# Colors
NAVY = colors.HexColor("#1B3A6B")
WHITE = colors.white
LIGHT_GRAY = colors.HexColor("#F5F7FA")
MED_GRAY = colors.HexColor("#E2E8F0")
GREEN = colors.HexColor("#27AE60")
RED = colors.HexColor("#E74C3C")
ORANGE = colors.HexColor("#F39C12")

W, M = A4[0], 14 * mm
USABLE = W - 2 * M  # 516pt

# Style counter (LAW 6)
_sc = [0]
def S(name="", **kw):
    _sc[0] += 1
    return ParagraphStyle(f"dyn_{_sc[0]}_{name}", **kw)

def P(text, style):
    return Paragraph(str(text), style)


def generate_pdf(analysis: dict, df, company_name: str = "Your Practice") -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=M, rightMargin=M, topMargin=M, bottomMargin=M
    )
    story = []

    # Styles
    title_s = S("title", fontSize=28, fontName="Helvetica-Bold", textColor=WHITE, alignment=1, leading=34)
    sub_s = S("sub", fontSize=14, fontName="Helvetica", textColor=WHITE, alignment=1, leading=18)
    h1_s = S("h1", fontSize=16, fontName="Helvetica-Bold", textColor=NAVY, leading=20)
    body_s = S("body", fontSize=10, fontName="Helvetica", leading=14, textColor=colors.HexColor("#333333"))
    bold_s = S("bold", fontSize=10, fontName="Helvetica-Bold", leading=14)
    th_s = S("th", fontSize=9, fontName="Helvetica-Bold", textColor=WHITE, alignment=1)
    td_s = S("td", fontSize=9, fontName="Helvetica", leading=12)
    td_c = S("tdc", fontSize=9, fontName="Helvetica", leading=12, alignment=1)
    small_s = S("small", fontSize=8, fontName="Helvetica", textColor=colors.gray, alignment=1)

    summary = analysis.get("summary", {})
    date_str = datetime.now().strftime("%B %d, %Y")

    # ── COVER PAGE ──────────────────────────────────────────────
    cover_data = [[P("RCM DENIAL ANALYZER PRO", title_s)]]
    cover_tbl = Table(cover_data, colWidths=[USABLE])
    cover_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [NAVY]),
        ("TOPPADDING", (0, 0), (-1, -1), 24),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
    ]))
    story.append(cover_tbl)
    story.append(Spacer(1, 8))

    sub_data = [[P(f"Denial Analysis Report — {company_name}", sub_s)],
                [P(date_str, sub_s)]]
    sub_tbl = Table(sub_data, colWidths=[USABLE])
    sub_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#2C5282")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(sub_tbl)
    story.append(Spacer(1, 14))

    # KPI boxes (3 across)
    denial_rate = summary.get("denial_rate_pct", 0)
    recoverable = summary.get("estimated_recoverable_amount", 0)
    recovery_rate = summary.get("recovery_rate_pct", 0)

    kpi_headers = [
        [P("DENIAL RATE", th_s), P("RECOVERABLE $", th_s), P("RECOVERY RATE", th_s)]
    ]
    kpi_values = [
        [P(f"{denial_rate:.1f}%", S("kv", fontSize=24, fontName="Helvetica-Bold", textColor=NAVY, alignment=1)),
         P(f"${recoverable:,.0f}", S("kv2", fontSize=24, fontName="Helvetica-Bold", textColor=GREEN, alignment=1)),
         P(f"{recovery_rate:.0f}%", S("kv3", fontSize=24, fontName="Helvetica-Bold", textColor=ORANGE, alignment=1))]
    ]
    kpi_tbl = Table(kpi_headers + kpi_values, colWidths=[172, 172, 172])
    kpi_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("BACKGROUND", (0, 1), (-1, 1), LIGHT_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(kpi_tbl)
    story.append(Spacer(1, 14))

    # Stats row
    stats_data = [[
        P("Total Claims", th_s),
        P("Total Denied $", th_s),
        P("Report Date", th_s),
        P("Generated By", th_s),
    ], [
        P(str(summary.get("total_claims", 0)), td_c),
        P(f"${summary.get('total_denied_amount', 0):,.2f}", td_c),
        P(date_str, td_c),
        P("RCM Denial Analyzer Pro", td_c),
    ]]
    stats_tbl = Table(stats_data, colWidths=[129, 129, 129, 129])
    stats_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("BACKGROUND", (0, 1), (-1, 1), WHITE),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
    ]))
    story.append(stats_tbl)
    story.append(Spacer(1, 14))

    # Immediate actions on cover
    actions = analysis.get("immediate_actions", [])
    if actions:
        act_rows = [[P("IMMEDIATE ACTIONS", th_s), P("", th_s)]]
        for i, a in enumerate(actions[:3], 1):
            act_rows.append([P(f"{i}.", td_c), P(a, td_s)])
        act_tbl = Table(act_rows, colWidths=[30, USABLE - 30])
        act_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("SPAN", (0, 0), (-1, 0)),
            ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GRAY),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ]))
        story.append(act_tbl)

    story.append(PageBreak())

    # ── PAGE 2: TOP DENIAL PATTERNS ─────────────────────────────
    story.append(P("Top Denial Patterns", h1_s))
    story.append(Spacer(1, 8))

    patterns = analysis.get("top_patterns", [])
    if patterns:
        pat_headers = [[
            P("Code", th_s), P("Label", th_s), P("Freq %", th_s),
            P("Amount $", th_s), P("Recovery $", th_s), P("Priority", th_s)
        ]]
        pat_rows = []
        for p in patterns:
            pri = p.get("priority", "MEDIUM")
            pri_color = RED if pri == "HIGH" else (ORANGE if pri == "MEDIUM" else GREEN)
            pat_rows.append([
                P(p.get("denial_code", ""), td_c),
                P(p.get("label", ""), td_s),
                P(f"{p.get('frequency_pct', 0):.1f}%", td_c),
                P(f"${p.get('total_amount', 0):,.0f}", td_c),
                P(f"${p.get('recoverable_amount', 0):,.0f}", td_c),
                P(pri, S(f"pri_{pri}", fontSize=9, fontName="Helvetica-Bold",
                         textColor=pri_color, alignment=1)),
            ])

        pat_tbl = Table(pat_headers + pat_rows, colWidths=[60, 150, 60, 82, 82, 82])
        pat_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ]))
        story.append(pat_tbl)
        story.append(Spacer(1, 12))

        # Fix actions
        story.append(P("Fix Actions by Denial Code", h1_s))
        story.append(Spacer(1, 6))
        for p in patterns:
            fix_rows = [
                [P(f"{p.get('denial_code')} — {p.get('label', '')}", th_s), P("", th_s)],
                [P("Root Cause:", bold_s), P(p.get("root_cause", ""), td_s)],
                [P("Fix Action:", bold_s), P(p.get("fix_action", ""), td_s)],
                [P("Recovery Prob:", bold_s), P(f"{p.get('recovery_probability_pct', 0):.0f}%", td_s)],
            ]
            fix_tbl = Table(fix_rows, colWidths=[100, USABLE - 100])
            fix_tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("SPAN", (0, 0), (-1, 0)),
                ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GRAY),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
            ]))
            story.append(fix_tbl)
            story.append(Spacer(1, 8))

    story.append(PageBreak())

    # ── PAGE 3: PAYER ANALYSIS ──────────────────────────────────
    story.append(P("Payer Analysis", h1_s))
    story.append(Spacer(1, 8))

    payer_analysis = analysis.get("payer_analysis", [])
    if payer_analysis:
        pay_headers = [[
            P("Payer", th_s), P("Denials", th_s), P("Total $", th_s),
            P("Top Code", th_s), P("Recommended Action", th_s)
        ]]
        pay_rows = []
        for pa in payer_analysis:
            pay_rows.append([
                P(pa.get("payer", ""), td_s),
                P(str(pa.get("denial_count", 0)), td_c),
                P(f"${pa.get('total_amount', 0):,.0f}", td_c),
                P(pa.get("most_common_denial", ""), td_c),
                P(pa.get("recommended_action", ""), td_s),
            ])
        pay_tbl = Table(pay_headers + pay_rows, colWidths=[90, 55, 70, 65, 236])
        pay_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ]))
        story.append(pay_tbl)
        story.append(Spacer(1, 14))

    # 30-day plan
    plan = analysis.get("30_day_recovery_plan", "")
    if plan:
        story.append(P("30-Day Recovery Plan", h1_s))
        story.append(Spacer(1, 6))
        plan_data = [[P(plan, td_s)]]
        plan_tbl = Table(plan_data, colWidths=[USABLE])
        plan_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ]))
        story.append(plan_tbl)
        story.append(Spacer(1, 14))

    # Footer note
    story.append(Spacer(1, 20))
    story.append(P("Generated by RCM Denial Analyzer Pro · AI-powered by Claude · For internal use only", small_s))

    doc.build(story)
    buf.seek(0)
    return buf.read()
